readme, compile fix

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,13 +1,20 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
-# Last updated: June 20, 2025
+# Last updated: June 15, 2025 05:02 AM UTC
+echo -en '\n'
 
+# Fail fast
 set -e
 
+# Debug
+# set -x
+
+# Parse and derive params
 BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
-LP_DIR=$(cd "$(dirname "$0")"; cd ..; pwd)
+
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
 function error() {
   echo " !     $*" >&2
@@ -19,15 +26,22 @@ function topic() {
 }
 
 function indent() {
-  sed 's/^/       /'
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
 }
 
-# Firefox & Geckodriver versions
+# Config
+# Hardcoded available stable versions
+# Use it to manually update the version as per https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html
 VERSION_FIREFOX=139.0.4
 VERSION_GECKODRIVER=0.36.0
 LANG=en-US
 PLATFORM=linux64
 
+# Buildpack URL
 ARCHIVE_NAME_FIREFOX=firefox
 ARCHIVE_NAME_GECKODRIVER=geckodriver
 FILE_NAME_FIREFOX=${ARCHIVE_NAME_FIREFOX}-${VERSION_FIREFOX}.tar.xz
@@ -35,7 +49,7 @@ FILE_NAME_GECKODRIVER=${ARCHIVE_NAME_GECKODRIVER}-v${VERSION_GECKODRIVER}-${PLAT
 BUILDPACK_FIREFOX_PACKAGE="https://download.mozilla.org/?product=firefox-${VERSION_FIREFOX}-SSL&os=${PLATFORM}&lang=${LANG}"
 BUILDPACK_GECKODRIVER_PACKAGE="https://github.com/mozilla/geckodriver/releases/download/v${VERSION_GECKODRIVER}/${FILE_NAME_GECKODRIVER}"
 
-# Supported stack
+# Install correct dependencies according to $STACK
 case "$STACK" in
   "heroku-24" | "heroku-22" | "heroku-20" | "heroku-18" | "heroku-16")
     PACKAGES="
@@ -65,76 +79,100 @@ case "$STACK" in
     "
     ;;
   *)
-    error "Must be on a supported Heroku stack (heroku-24, -22, -20, -18, -16)"
+    error "Must be on a supported Heroku version: heroku-24, heroku-22, heroku-20, heroku-18, heroku-16"
 esac
 
-# Clear old apt cache
-if [ ! -f "$CACHE_DIR/PURGED_CACHE_V1" ]; then
-  topic "Purging apt cache"
-  rm -rf "$CACHE_DIR/apt" "$CACHE_DIR/archives" "$CACHE_DIR/lists"
-  touch "$CACHE_DIR/PURGED_CACHE_V1"
+if [ ! -f $CACHE_DIR/PURGED_CACHE_V1 ]; then
+  topic "Purging cache"
+  rm -rf $CACHE_DIR/apt
+  rm -rf $CACHE_DIR/archives
+  rm -rf $CACHE_DIR/lists
+  touch $CACHE_DIR/PURGED_CACHE_V1
 fi
 
-# Setup apt dirs
+topic "Installing correct dependencies."
+
 APT_CACHE_DIR="$CACHE_DIR/apt/cache"
 APT_STATE_DIR="$CACHE_DIR/apt/state"
-mkdir -p "$APT_CACHE_DIR/archives/partial" "$APT_STATE_DIR/lists/partial"
+
+mkdir -p "$APT_CACHE_DIR/archives/partial"
+mkdir -p "$APT_STATE_DIR/lists/partial"
+
 APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
 
 topic "Updating apt caches"
 apt-get $APT_OPTIONS update | indent
 
-# Download apt packages
 for PACKAGE in $PACKAGES; do
-  topic "Fetching .debs for $PACKAGE"
-  apt-get $APT_OPTIONS -y -d install --reinstall $PACKAGE | indent
+  if [[ $PACKAGE == *deb ]]; then
+    PACKAGE_NAME=$(basename $PACKAGE .deb)
+    PACKAGE_FILE=$APT_CACHE_DIR/archives/$PACKAGE_NAME.deb
+
+    topic "Fetching $PACKAGE"
+    curl -s -L -z $PACKAGE_FILE -o $PACKAGE_FILE $PACKAGE 2>&1 | indent
+  else
+    topic "Fetching .debs for $PACKAGE"
+    apt-get $APT_OPTIONS -y -d install --reinstall $PACKAGE | indent
+  fi
 done
 
-# Extract .debs into .apt directory
-mkdir -p "$BUILD_DIR/.apt"
-for DEB in "$APT_CACHE_DIR"/archives/*.deb; do
-  topic "Installing $(basename "$DEB")"
-  dpkg -x "$DEB" "$BUILD_DIR/.apt/"
+mkdir -p $BUILD_DIR/.apt
+
+for DEB in $(ls -1 $APT_CACHE_DIR/archives/*.deb); do
+  topic "Installing $(basename $DEB)"
+  dpkg -x $DEB $BUILD_DIR/.apt/
 done
 
-# Firefox
-if [ ! -f "$CACHE_DIR/$FILE_NAME_FIREFOX" ]; then
-  topic "Downloading Firefox"
-  curl -sSL "$BUILDPACK_FIREFOX_PACKAGE" -o "$CACHE_DIR/$FILE_NAME_FIREFOX"
+# Install Firefox
+mkdir -p $CACHE_DIR
+if ! [ -e $CACHE_DIR/$FILE_NAME_FIREFOX ]; then
+  topic "Fetching Firefox package from ${BUILDPACK_FIREFOX_PACKAGE}"
+  curl $BUILDPACK_FIREFOX_PACKAGE -L -o $CACHE_DIR/$FILE_NAME_FIREFOX
 fi
 
-topic "Extracting Firefox to vendor"
-mkdir -p "$BUILD_DIR/vendor/firefox"
-tar -xJf "$CACHE_DIR/$FILE_NAME_FIREFOX" --strip-components=1 -C "$BUILD_DIR/vendor/firefox"
+topic "Extracting Firefox binaries to ${BUILD_DIR}/vendor/${ARCHIVE_NAME_FIREFOX}"
+mkdir -p $CACHE_DIR/$ARCHIVE_NAME_FIREFOX
+mkdir -p $BUILD_DIR/vendor
+tar -xJf $CACHE_DIR/$FILE_NAME_FIREFOX -C $CACHE_DIR
+mv $CACHE_DIR/$ARCHIVE_NAME_FIREFOX $BUILD_DIR/vendor/
 
-# Geckodriver
-if [ ! -f "$CACHE_DIR/$FILE_NAME_GECKODRIVER" ]; then
-  topic "Downloading Geckodriver"
-  curl -sSL "$BUILDPACK_GECKODRIVER_PACKAGE" -o "$CACHE_DIR/$FILE_NAME_GECKODRIVER"
+# Install Geckodriver
+if ! [ -e $CACHE_DIR/$FILE_NAME_GECKODRIVER ]; then
+  topic "Fetching Geckodriver package from ${BUILDPACK_GECKODRIVER_PACKAGE}"
+  curl $BUILDPACK_GECKODRIVER_PACKAGE -L -o $CACHE_DIR/$FILE_NAME_GECKODRIVER
 fi
 
-topic "Extracting Geckodriver"
-mkdir -p "$BUILD_DIR/vendor/geckodriver"
-tar -xzf "$CACHE_DIR/$FILE_NAME_GECKODRIVER" -C "$BUILD_DIR/vendor/geckodriver"
-chmod +x "$BUILD_DIR/vendor/geckodriver/geckodriver"
+topic "Extracting Geckodriver binaries to ${BUILD_DIR}/vendor/${ARCHIVE_NAME_GECKODRIVER}"
+mkdir -p $CACHE_DIR/$ARCHIVE_NAME_GECKODRIVER
+mkdir -p $BUILD_DIR/vendor/$ARCHIVE_NAME_GECKODRIVER
+tar -xzf $CACHE_DIR/$FILE_NAME_GECKODRIVER -C $CACHE_DIR
+chmod +x $CACHE_DIR/$ARCHIVE_NAME_GECKODRIVER
+mv $CACHE_DIR/$ARCHIVE_NAME_GECKODRIVER $BUILD_DIR/vendor/$ARCHIVE_NAME_GECKODRIVER/
 
-chmod +x "$BUILD_DIR/vendor/firefox/firefox"
-
-# Set environment
-topic "Setting environment variables"
-mkdir -p "$BUILD_DIR/.profile.d"
-cat <<EOF > "$BUILD_DIR/.profile.d/000_firefox_env.sh"
-export PATH="\$HOME/.apt/usr/bin:\$HOME/vendor/firefox:\$HOME/vendor/geckodriver:\$PATH"
-export LD_LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$HOME/vendor/firefox:\$HOME/vendor/geckodriver:\$LD_LIBRARY_PATH"
-export LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$HOME/vendor/firefox:\$HOME/vendor/geckodriver:\$LIBRARY_PATH"
+topic "Setting paths"
+mkdir -p $BUILD_DIR/.profile.d
+cat <<EOF >$BUILD_DIR/.profile.d/000_apt.sh
+export PATH="\$HOME/.apt/usr/bin:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$PATH"
+export LD_LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$LD_LIBRARY_PATH"
+export LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$LIBRARY_PATH"
 export INCLUDE_PATH="\$HOME/.apt/usr/include:\$HOME/.apt/usr/include/x86_64-linux-gnu:\$INCLUDE_PATH"
 export CPATH="\$INCLUDE_PATH"
 export CPPPATH="\$INCLUDE_PATH"
 export PKG_CONFIG_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/i386-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/pkgconfig:\$PKG_CONFIG_PATH"
-export TMPDIR="\$HOME/tmp"
+export TMPDIR="\$BUILD_DIR/tmp"
 EOF
 
-# Give environment to later buildpacks
-export | grep -E ' (PATH|LD_LIBRARY_PATH|LIBRARY_PATH|INCLUDE_PATH|CPATH|CPPPATH|PKG_CONFIG_PATH)=' > "$LP_DIR/export"
+export PATH="$BUILD_DIR/.apt/usr/bin:$PATH:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$PATH"
+export LD_LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$LIBRARY_PATH"
+export LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$LIBRARY_PATH"
+export INCLUDE_PATH="$BUILD_DIR/.apt/usr/include:$BUILD_DIR/.apt/usr/include/x86_64-linux-gnu:$INCLUDE_PATH"
+export CPATH="$INCLUDE_PATH"
+export CPPPATH="$INCLUDE_PATH"
+export PKG_CONFIG_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu/pkgconfig:$BUILD_DIR/.apt/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
+export TMPDIR="\$BUILD_DIR/tmp"
 
-topic "Done installing Firefox and Geckodriver"
+#Give environment to later buildpacks
+export | grep -E -e ' (PATH|LD_LIBRARY_PATH|LIBRARY_PATH|INCLUDE_PATH|CPATH|CPPPATH|PKG_CONFIG_PATH)='  > "$LP_DIR/export"
+
+topic "Rewrite package-config files"
+find $BUILD_DIR/.apt -type f -ipath '*/pkgconfig/*.pc' | xargs --no-run-if-empty -n 1 sed -i -e 's!^prefix=\(.*\)$!prefix='"$BUILD_DIR"'/.apt\1!g'
